# Generated by Django 3.1.6 on 2021-05-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '__first__'),
        ('speciality_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speciality_groups.group', verbose_name='group')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='student')),
            ],
            options={
                'verbose_name': 'Group_Enrollment',
                'verbose_name_plural': 'Group_Enrollments',
            },
        ),
    ]
