# Generated by Django 3.1.6 on 2021-05-07 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department', verbose_name='department'),
        ),
    ]
