# Generated by Django 3.1.6 on 2021-05-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='references/'),
        ),
    ]
