# Generated by Django 2.2.13 on 2021-05-22 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_auto_20210511_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
